#!/usr/bin/env python3
import json
from sys import argv
from subprocess import call
from subprocess import Popen, PIPE

with open("/home/fusion809/OBS/home:fusion809:arch_extra/nodejs-" + argv[1] + "/src/package/package.json") as json_file:
    json_data = json.load(json_file)
    deps = json_data["dependencies"]
    LEN=len(deps)
    i=0
    DEP=list()
    print(DEP)
    for key, value in deps.items():
        DEP.append(key)
        i = i+1
        call(["cpobsn", key, argv[1]])
    p=Popen(["depends"] + DEP, stdout=PIPE)
    output, err = p.communicate(b"input data that is passed to subprocess' stdin")
    rc = p.returncode
    out=output.rstrip()
    call(["moddepends", "nodejs-" + argv[1], out])
    for idx in range(i-1):
        call(["npm2OBS", DEP[idx]])
