#!/usr/bin/env python3
import json
from sys import argv
from subprocess import call
from subprocess import Popen, PIPE

# argv[1] is the command-line option provided to the npm2OBS script and is essentially a NPM package's name
# it is converted to a suitable package named for Arch Linux
with open("/home/fusion809/OBS/home:fusion809:arch_extra/nodejs-" + argv[1] + "/src/package/package.json") as json_file:
    json_data = json.load(json_file)
    deps = json_data["dependencies"]
    LEN=len(deps)
    i=0
    DEP=list()
    print(DEP)

    # The following initially creates the necessary OBS project directories for the package's direct deps and gets them ready.
    for key, value in deps.items():
        DEP.append(key)
        i = i+1
        call(["cpobsn", key, argv[1]])

    p=Popen(["depends"] + DEP, stdout=PIPE)
    output, err = p.communicate(b"input data that is passed to subprocess' stdin")
    rc = p.returncode

    # Out is a shell-script readable list of the dependencies for which OBS packages were created earlier.
    out=output.rstrip()

    # This should add these deps to the depends=() array of the original PKGBUILD.
    call(["moddepends", "nodejs-" + argv[1], out])

    # This re-runs this script for each of the dependencies listed in out.
    for idx in range(i-1):
        call(["npm2OBS", DEP[idx]])
